### ISSUE TITLE
custom version tag

### ISSUE THREAD

**Issue by royaltm** [bchr02/node-pre-gyp-github#10]
First of all, nice work - saved me some time.

The issue for me however is that I was generating tag names with "v" prefix, e.g. "v1.0.0".

Currently your script uses hardcoded `this.package_json.version` as a release tag name, but it would be great if one could simple pass the version tag name via arguments to `bin/node-pre-gyp-github`.

BTW. I am using access token with only "notifications, public_repo, repo_deployment" access flags enabled and it works fine. Probably "notifications" are not even needed, but can not confirm that yet.

**Comment by bchr02** [comment]
@royal thanks. 

Yes, this is a good suggestion. I will add it.

And thanks for the info on the access you are using. 

- sent from iPhone.

**Comment by royaltm** [comment]
I've created a pull request. You might not like it due to the breaking change. However I think you'll might find interesting the idea about {version}.

**Comment by bchr02** [comment]
@royal can you change it so it's not a breaking change? I think it could be done. 

- sent from iPhone.

**Comment by royaltm** [comment]
In order to do that i would have change uploadAssets() - instead of flat scan of the directory (stage_dir / tag_name) to it would need to deep scan the whole stage_dir until the file is found. Alternatively it could test for (stage_dir / tag_name) first and fall back to (stage_dir). Maybe I'll try the second approach.

**Comment by royaltm** [comment]
done

**Comment by bchr02** [comment]
@royaltm Please see my code comments inline: https://github.com/bchr02/node-pre-gyp-github/pull/11/files#diff-168726dbe96b3ce427e7fedce31bb0bc
thanks.

**Comment by bchr02** [comment]
Also, [line 63](https://github.com/bchr02/node-pre-gyp-github/pull/11/files#diff-168726dbe96b3ce427e7fedce31bb0bcR63) needs to be changed to ```options.tag_name```

**Comment by bchr02** [comment]
*I just deleted my previous comment about needing to update line 63. It was a mistake.*

**Comment by royaltm** [comment]
Please see my answers to your comments.

**Comment by bchr02** [comment]
Done with: https://github.com/bchr02/node-pre-gyp-github/pull/12

Instead of customizing tag via an option we implemented via a new package.json's binary.remote_path property.
