### ISSUE TITLE
validation failed: invalid release target_commitish

### ISSUE THREAD

**Issue by tuananh** [bchr02/node-pre-gyp-github#21]
```
/Users/travis/.nvm/versions/node/v8.9.1/lib/node_modules/node-pre-gyp-github/index.js:170

				if(err) throw err;

				        ^

Error: {"message":"Validation Failed","errors":[{"resource":"Release","code":"invalid","field":"target_commitish"}],"documentation_url":"https://developer.github.com/v3/repos/releases/#create-a-release"}
```

https://travis-ci.org/tuananh/fasttext-native/jobs/310894416

any idea what i did wrong here?

**Comment by bchr02** [comment]
The reason this is happening is because within your repo it appears you don't have a "master" branch and instead only one called "develop". node-pre-gyp-github will only publish releases to the master branch. There currently is not a feature for using another branch.

**Comment by tuananh** [comment]
I see. Thank you.
