### ISSUE TITLE
Cool idea

### ISSUE THREAD

**Issue by cscott** [bchr02/node-pre-gyp-github#3]
I've been doing something similar for a while; see:
https://github.com/cscott/node-icu-bidi
https://github.com/cscott/node-php-embed
etc.

Perhaps you can borrow some ideas from my scripts?  I've been too lazy to actually package everything up as a nice standalone npm packages, glad to see you're doing that.

**Comment by bchr02** [comment]
Thanks @cscott. I'll take a look.

**Comment by springmeyer** [comment]
I like @cscott's use of `node-pre-gyp reveal` which should ensure that the right local paths are used no matter the variety of options you might use (Debug builds, various archs, etc). In a quick look around node-pre-gyp-github I don't see

  - tests
  - continuous integration
  - or the use of `reveal`

So I'm hesitant to recommend this tool yet. I landed here trying to answer the question of whether it makes sense to recommend using this tool via the node-pre-gyp README (pre https://github.com/mapbox/node-pre-gyp/pull/108#issuecomment-151478779).

**Comment by bchr02** [comment]
@springmeyer Thanks for getting back to me on [this](https://github.com/mapbox/node-pre-gyp/pull/108#issuecomment-151478779). It makes sense to add each of those items, so I will do so.

**Task List:**
- [ ] tests
- [ ] continuous integration
- [ ] use of reveal

**Comment by springmeyer** [comment]
great @bchr02. The simplicity of https://github.com/cscott/node-icu-bidi/blob/master/scripts/publish.js is also appealing so you might look for other smart things it does?

**Comment by bchr02** [comment]
> The simplicity of https://github.com/cscott/node-icu-bidi/blob/master/scripts/publish.js is also appealing so you might look for other smart things it does?

okay, I will do that.

**Comment by bchr02** [comment]
@springmeyer with https://github.com/bchr02/node-pre-gyp-github/commit/73e8be34cd3d5fcb910b5c925a6b25af81dddb14 I have just added unit tests with over 97% line coverage. I still plan on adding CI and reveal, but maybe now this is enough for you to recommend this module. :smile:

**Comment by bchr02** [comment]
@springmeyer now at 100% coverage!

**Comment by springmeyer** [comment]
Thanks @bchr02 - Yes, it is. I'm traveling - perhaps you could make a PR against node-pre-gyp adding mention and usage to the readme?

**Comment by bchr02** [comment]
@springmeyer Sorry for taking so long. As you requested, I have made mention and submitted https://github.com/mapbox/node-pre-gyp/pull/216 Thank you.
