### ISSUE TITLE
HttpError "Not found"

### ISSUE THREAD

**Issue by cisaacson** [bchr02/node-pre-gyp-github#33]
I am getting this error using `node-pre-gyp-github` version 1.4.3:

```
(node:23711) UnhandledPromiseRejectionWarning: HttpError: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository"}
    at response.text.then.message (/Users/coryisaacson/git/rtip-rs/flatbuffer-idl-parser-js/node_modules/node-pre-gyp-github/node_modules/@octokit/rest/lib/request/request.js:72:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I saw this was an issue with an earlier release but I'm getting it now with this one. I am installed `@octokit/rest": "^16.35.2` to ensure I have the latest.

Any recommendations appreciated. I have a valid github token and the repo is definitely valid too.

**Comment by cisaacson** [comment]
I added the rights of `write:packages` and `read:packages` to those recommended in the doc and it worked. This automatically selects full repo access. Would be good to update the documentation. If someone can confirm this I am happy to provide a pull request for the doc.

**Comment by Richienb** [comment]
In order for the script to access a public repository to update the assets, you need to select the **public_repo** scope.

**Comment by daniellockyer** [comment]
Closing this as the documentation lists the `public_repo` scope 🙂
