### ISSUE TITLE
package-lock.json is listed in .gitignore

### ISSUE THREAD

**Issue by justinkambic** [bchr02/node-pre-gyp-github#36]
Why do we have `package-lock.json` ignored?

This file [is meant](https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json) to be committed to the repo's version control, should we not remove that entry?

**Comment by justinkambic** [comment]
I created a PR that removes that entry from `.gitignore` and bumps the version of two packages that were out of date and causing `npm` to provide high/critical vulnerability warnings. https://github.com/bchr02/node-pre-gyp-github/pull/37

**Comment by daniellockyer** [comment]
Hey @justinkambic, I've just fixed this issue 🙂 I'll push dependency bumps soon
