### ISSUE TITLE
Release X.X.X not found. Every single time

### ISSUE THREAD

**Issue by WebReflection** [bchr02/node-pre-gyp-github#6]
I'm not sure I'm doing something wrong but I've tried them all.

This is my [package.json](https://github.com/WebReflection/node-gtk/blob/master/package.json)
Maybe I'm dropping too many folders in [.npmignore](https://github.com/WebReflection/node-gtk/blob/master/.npmignore) ?

All I know is that it builds, everything is absolutely fine, but when it come to publishing, this is every time the error and installing does every time the fallback:
```
node-pre-gyp-github publish
Release 0.0.12 not found, so a draft release was created. YOU MUST MANUALLY PUBLISH THIS DRAFT WITHIN GITHUB FOR IT TO BE ACCESSIBLE.
Stage directory path: /home/webreflection/code/node-gtk/build/stage
```

Thanks for any sort of help!

**Comment by WebReflection** [comment]
Actually, never mind. I was excluding the build/Release folder from both gitignore and npmignore, I guess that was kinda the problem.

Apologies for bothering. Thanks for thsi project.

**Comment by bchr02** [comment]
@WebReflection No worries. I'm glad you got it working.
